export const TOPICS = [
  {
    id: "url",
    icon: "🌐",
    tag: "Networking & Web",
    tagColor: "#06d6a0",
    title: "What happens when you type a URL and press Enter?",
    desc: "DNS, TCP, TLS, load balancers, servers — the complete journey visualized.",
    steps: 12,
    time: "~8 min",
    available: true,
  },
  {
    id: "cdn",
    icon: "⚡",
    tag: "Networking & Web",
    tagColor: "#06d6a0",
    title: "How does a CDN serve files faster?",
    desc: "Edge nodes, Anycast routing, cache hits/misses and invalidation — visualized with real HTTP headers.",
    steps: 10,
    time: "~7 min",
    available: true,
  },
  {
    id: "loadbalancer",
    icon: "⚖️",
    tag: "Infrastructure",
    tagColor: "#118ab2",
    title: "How does a load balancer actually work?",
    desc: "Round robin, least connections, health checks — visualized step by step.",
    steps: 8,
    time: "~6 min",
    available: false,
  },
  {
    id: "photos",
    icon: "📸",
    tag: "Storage & Data",
    tagColor: "#ffd166",
    title: "How Google Photos automatically backs up your photos",
    desc: "From camera roll to distributed object storage — the full upload pipeline.",
    steps: 9,
    time: "~7 min",
    available: false,
  },
  {
    id: "db-index",
    icon: "🗄️",
    tag: "Storage & Data",
    tagColor: "#ffd166",
    title: "How database indexes make queries 1000x faster",
    desc: "B-trees, full table scans, query planners — visualized with real SQL.",
    steps: 8,
    time: "~6 min",
    available: false,
  },
  {
    id: "oauth",
    icon: "🔒",
    tag: "Auth & Security",
    tagColor: "#fd79a8",
    title: 'How OAuth & "Sign in with Google" works',
    desc: "Authorization codes, access tokens, refresh tokens — the complete flow.",
    steps: 10,
    time: "~8 min",
    available: false,
  },
  {
    id: "compiler",
    icon: "⚙️",
    tag: "Code & Compilation",
    tagColor: "#a29bfe",
    title: "How your code goes from text to machine instructions",
    desc: "Lexer → parser → AST → IR → machine code. Every step explained.",
    steps: 11,
    time: "~9 min",
    available: false,
  },
  {
    id: "docker",
    icon: "🐳",
    tag: "Infrastructure",
    tagColor: "#118ab2",
    title: "How Docker containers are isolated from each other",
    desc: "Namespaces, cgroups, and the Linux kernel magic behind containers.",
    steps: 9,
    time: "~7 min",
    available: false,
  },
  {
    id: "redis",
    icon: "💾",
    tag: "Storage & Data",
    tagColor: "#ffd166",
    title: "How Redis serves 1 million requests per second",
    desc: "In-memory storage, single-threaded event loop, and data structures.",
    steps: 7,
    time: "~5 min",
    available: false,
  },
];

export const CATEGORIES = [
  "All",
  "Networking & Web",
  "Infrastructure",
  "Storage & Data",
  "Auth & Security",
  "Code & Compilation",
];