export const OAUTH_STEP_DETAILS = [
    {
        title: "1. Authorization Request",
        phase: "Phase 1: Initiation",
        analogy: "You arrive at a hotel (Client App) and ask to enter a room. The front desk tells you they need proof of identity, so they send you to the official security office (Auth Server).",
        summary: "When the user clicks 'Login with Google/GitHub', the Client Application redirects the user's browser to the Authorization Server. It asks for specific permissions (scopes) and provides a callback URL.",
        technical: [
            "Client ID: A public identifier for the app requesting access.",
            "Redirect URI: Where the Auth Server should send the user after a successful login.",
            "Scope: The specific permissions being requested (e.g., 'read:email').",
            "State: A random string generated by the client to prevent Cross-Site Request Forgery (CSRF) attacks."
        ],
        code: `// HTTP Redirect (302) to the Authorization Server:
GET https://auth.server.com/authorize
  ?response_type=code
  &client_id=YOUR_CLIENT_ID
  &redirect_uri=https://yourapp.com/callback
  &scope=profile email
  &state=xyz123random`
    },
    {
        title: "2. Authentication & Consent",
        phase: "Phase 2: User Action",
        analogy: "At the security office, you show your driver's license to prove who you are. The officer asks, 'Do you consent to letting the hotel know your name and email?'",
        summary: "The Authorization Server prompts the user to log in (if they aren't already) and presents a consent screen. The user must explicitly grant the Client Application the permissions it requested.",
        technical: [
            "Authentication: The Auth Server verifies the user's identity via passwords, MFA, or biometrics.",
            "Authorization / Consent: The user grants the 'delegated access' to the Client App.",
            "Security: The Client Application NEVER sees the user's password. It is entered directly on the Auth Server."
        ],
        code: `<!-- Conceptual Consent Screen -->
<div class="consent-modal">
  <h2>"YourApp" wants to access your Google Account</h2>
  <ul>
    <li>View your email address</li>
    <li>View your basic profile info</li>
  </ul>
  <button>Allow</button> <button>Deny</button>
</div>`
    },
    {
        title: "3. Authorization Code Grant",
        phase: "Phase 3: Delegation",
        analogy: "You agree, and the security officer hands you a sealed, temporary paper slip (Auth Code) to carry back to the hotel front desk.",
        summary: "Once the user consents, the Authorization Server redirects the user's browser back to the Client Application's `redirect_uri`. It attaches a temporary, single-use Authorization Code to the URL.",
        technical: [
            "Authorization Code: A short-lived (usually valid for 1-10 minutes) token.",
            "Front-Channel: This code travels through the user's browser, which means it is visible and potentially interceptable.",
            "State Verification: The client app checks if the returned 'state' matches the one it originally sent to prevent CSRF."
        ],
        code: `// Browser is redirected back to the Client App:
HTTP/1.1 302 Found
Location: https://yourapp.com/callback?code=SPL_CODE_9876&state=xyz123random

// The backend extracts the code:
const authCode = req.query.code;
const state = req.query.state;`
    },
    {
        title: "4. Token Exchange Request",
        phase: "Phase 4: Verification",
        analogy: "The hotel desk takes your paper slip, sneaks through a secure back door, and hands it to the security office along with their hotel business license to get your actual plastic room key.",
        summary: "The Client Application takes the Authorization Code and makes a secure, backend-to-backend request to the Auth Server to exchange it for an Access Token.",
        technical: [
            "Back-Channel: This request happens purely server-to-server. The browser is not involved.",
            "Client Secret: The Client App authenticates itself to the Auth Server using its hidden Client Secret.",
            "Security: Because the exchange requires the Client Secret, a malicious actor who stole the Auth Code in Phase 3 cannot use it."
        ],
        code: `// Secure Server-to-Server POST request:
POST https://auth.server.com/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
&code=SPL_CODE_9876
&redirect_uri=https://yourapp.com/callback
&client_id=YOUR_CLIENT_ID
&client_secret=YOUR_SUPER_SECRET_KEY`
    },
    {
        title: "5. Token Issuance",
        phase: "Phase 4: Verification",
        analogy: "The security office verifies the hotel's license and the paper slip, burns the paper slip, and prints out a programmable plastic keycard (Access Token).",
        summary: "The Auth Server validates the Authorization Code and the Client Secret. If valid, it returns an Access Token (and often a Refresh Token) back to the Client Application.",
        technical: [
            "Access Token: Often a JWT (JSON Web Token), used to access protected resources.",
            "Refresh Token: A long-lived token used to get a new Access Token when the current one expires without making the user log in again.",
            "Expires_in: The lifespan of the access token in seconds (e.g., 3600 for 1 hour)."
        ],
        code: `// Response from the Auth Server:
{
  "access_token": "eyJhbGciOiJIUzI1NiIsIn...",
  "token_type": "Bearer",
  "expires_in": 3600,
  "refresh_token": "def5020054...",
  "scope": "profile email"
}`
    },
    {
        title: "6. Resource Request",
        phase: "Phase 5: Data Access",
        analogy: "You take the plastic keycard, walk up to your room door, and swipe it. The door reads the card, confirms it's valid, and unlocks.",
        summary: "The Client Application finally has what it needs. It attaches the Access Token to an HTTP header and makes a request to the Resource Server (the API) to fetch the user's data.",
        technical: [
            "Bearer Token: The token is passed in the 'Authorization' header using the 'Bearer' schema.",
            "Stateless Validation: If the token is a JWT, the Resource Server can validate its signature locally without asking the Auth Server.",
            "Access Granted: The Resource Server checks the scopes and returns the requested data (like the user's profile JSON)."
        ],
        code: `// Fetching the user's profile from the API:
GET https://api.server.com/v1/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsIn...

// The API returns the protected data!`
    }
];